service: hackatren

plugins: 
 - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10

functions:
  train:
    handler: api/train.handler
    events: 
      - http:
          path: train/{direction}
          method: put  
  eta: 
    handler: api/eta.handler
    events: 
      - http:
          path: eta/{id}
          method: get
  tweets:
    handler: api/tweets.handler
    events: 
      - http:
          path: tweets
          method: get
  leaderboard:
    handler: api/leaderboard.handler
    events: 
      - http:
          path: leaderboard
          method: get
  points:
    handler: api/points.handler
    events: 
      - http:
          path: points
          method: post
  account:
    handler: api/account.handler
    events: 
      - http:
          path: account
          method: get
  register:
    handler: api/register.handler
    events: 
      - http:
          path: register
          method: post